from flask import Flask, render_template, request, jsonify, redirect, url_for
from src.task_manager.manager import TaskManager

app = Flask(__name__)


@app.route('/')
def index():
    """Home page route"""
    return render_template('index.html')


@app.route('/upload', methods=['POST'])
def upload_file():
    """Handle file upload and processing"""
    if 'file' not in request.files:
        return jsonify({'error': 'No file part'}), 400

    file = request.files['file']

    if file.filename == '':
        return jsonify({'error': 'No file selected'}), 400

    ts = TaskManager()
    task = ts.create_task(file)



    summary = {
        'filename': file.filename,
        'content': "This is a sample summary of the uploaded media file. In a real application, this would be generated by processing the audio/video content."
    }

    # Store summary in session or database for retrieval
    # For simplicity, we'll redirect to a summary page with the data as URL parameters
    return redirect(url_for('view_summary', filename=file.filename))


@app.route('/summary/<filename>')
def view_summary(filename):
    """Display the summary results"""
    # In a real app, you would retrieve the actual summary from a database
    # Here we're generating a sample summary
    summary = {
        'filename': filename,
        'content': "This video discusses the importance of renewable energy sources and their impact on reducing carbon emissions. The speaker highlights three main points: solar and wind power are becoming increasingly cost-effective, energy storage solutions are critical for widespread adoption, and government policies can accelerate the transition to clean energy."
    }
    return render_template('summary.html', summary=summary)


@app.route('/api/summary/<filename>', methods=['GET'])
def get_summary(filename):
    """API endpoint to get summary data in JSON format"""
    # In a real app, retrieve from database
    summary = {
        'filename': filename,
        'content': "This video discusses the importance of renewable energy sources and their impact on reducing carbon emissions.",
        'timestamp': '2023-06-15T14:30:00Z'
    }
    return jsonify(summary)


@app.errorhandler(404)
def page_not_found(e):
    """Handle 404 errors"""
    return render_template('404.html'), 404


if __name__ == '__main__':
    app.run(debug=True)