version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: src/dockerfiles/Dockerfile_dev
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./summaries:/app/summaries
      - ./app.py:/app/app.py
    depends_on:
      - ollama
      - openai_proxy
    command: python3.10 -m app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  openai_proxy:
    build:
      context: .
      dockerfile: src/dockerfiles/Dockerfile_proxy
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    volumes:
      - ./src/proxy/app.py:/app/app.py
    environment:
      - OLLAMA_API_BASE=http://ollama:11434
      - PORT=8000

volumes:
  ollama:
    external: true